name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Check test results
        run: |
          if [ ${{ steps.test.outcome }} == 'failure' ]; then
            echo "Tests failed. Exiting with failure status."
            exit 1
          fi
